name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20.x
      - name: Install npm packages
        run: npm ci
      - name: Lint
        run: npx eslint .
      - name: Test
        run: node ./test/lib.test.js
